### PR TITLE
chore(python): add Python 3.12 compatibility

### LINKED ISSUE #1809: Support Python 3.12
Blocked on `aiohttp` [update](https://github.com/aio-libs/aiohttp/issues/7675)

Other todos:
- [ ] Update builds to include Python 3.12
- [ ] Update classifiers & docs

### PR DESCRIPTION
**Pull request by stegayet**
Resolves #1809 

### Description

Run CI workflows against latest Python 3.12 beta (3.12b4 as of writing this PR), it gives an overall good idea of schemathesis compatibility with this Python version. 

### Checklist

- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [x] Added a changelog entry
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by Stranger6667** [comment]
Thanks, @stegayet!

**Comment by stegayet** [comment]
Currently blocked by https://github.com/aio-libs/aiohttp/issues/7229 (and probably other issues :sweat_smile:)

**Comment by stegayet** [comment]
Also started working on bringing 3.12 compatibility for PyYAML in this PR: https://github.com/yaml/pyyaml/pull/739

**Comment by Stranger6667** [comment]
Thank you @stegayet ! I'll make a new release over the weekend :)

**Pull request merged**
