### PR TITLE
update --checks help message

### PR DESCRIPTION
**Pull request by markcmurphy**
### Description
Updated the help message that renders in online docs for `--checks` CLI option to describe how to enter multiple values

### CODE REVIEW

**Comment by Stranger6667** [comment]
Hi! thank you :) I'll merge as soon as the `httpx` issue is resolved

**Comment by markcmurphy** [comment]
> Hi! thank you :) I'll merge it as soon as the `httpx` issue is resolved

Thanks! I saw some of the GH Action checks failed; is the issue you're referring to something I need to fix?

**Comment by Stranger6667** [comment]
No no :) Hopefully, it will be resolved in #1615. I'll take a look today :)

**Comment by Stranger6667** [comment]
Thanks! It will be a part of the next release

**Pull request merged**
