### PR TITLE
feat: Support for colored output from docker container

### LINKED ISSUE #1170: [FEATURE] Support colored output from docker container
By default, Click autodetects support for ANSI color codes. In the case of running from Docker (e.g., the default Schemathesis image), colors will be absent. It might be nice to have an option like `--force-color` to force colored output, especially if the end-user knows that the host's terminal supports colors. This option should not be compatible with `--no-color` and if both are passed then we should have an error

### PR DESCRIPTION
**Pull request by mohebmithani**
- resolves #1170 
- updated run and replay function
- modified affected test cases
- modified doc

🚨Please review the [guidelines for contributing](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.rst) to this repository.

### Description

Please explain the changes you made here.

### Checklist

- [ ] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Added a changelog entry
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by Stranger6667 — CHANGES_REQUESTED** [review]
It is an amazing start! Could you, please, rebase and apply pre-commit changes? 
I see that some tests are failing which is a bit strange to me, could you, please, take a look? At first glance they don't seem relevant to changes in this PR

**Comment by mohebmithani** [comment]
> It is an amazing start! Could you, please, rebase and apply pre-commit changes? I see that some tests are failing which is a bit strange to me, could you, please, take a look? At first glance they don't seem relevant to changes in this PR

@Stranger6667 I think due to merge conflicts i clicked on GitHub's UI of resolve and that created another commit otherwise my all commit's are squashed. I'll look into this. 

But as for test cases some test cases were already failing in master branch that's why i didn't do anything about it. I'll look them again if i can resolve them but @Stranger6667 if you have time can you also look at them and guide me on how to resolve them

**Comment by Stranger6667** [comment]
Oh, I’ll take a look soon

**Comment by mohebmithani** [comment]
@Stranger6667 for now i've just added pre-commit issues and removed the master changes(Which i merged before creating a PR). 
for the test issues. I'll look into them. I just want your one favor. In your doc it is written to use tox but due to some reason i'm getting error while running tox. So i'm directly using pytest. Hope it won't create any issues right? also i'm adding error from tox maybe you know about this issue and can provide a few pointers:
AttributeError: module 'py' has no attribute 'io'

**Comment by Stranger6667** [comment]
Cool! Could you, please, resolve the final conflict with `changelog.rst`?

Yes, I think that using plain `pytest` should be fine - I didn't see the `tox` issue though. Maybe some older version would be compatible, not sure.

**Comment by mohebmithani** [comment]
> Cool! Could you, please, resolve the final conflict with `changelog.rst`?
> 
> Yes, I think that using plain `pytest` should be fine - I didn't see the `tox` issue though. Maybe some older version would be compatible, not sure.

Can you please guide me on how to merge conflicts without creating two commits? because merging from master creates another commit.I tried squashing but it is not working as still it is showing conflicts

**Comment by Stranger6667** [comment]
I think you can do a merge commit, then I'll do squash here in UI :) Probably it will be the easiest way to go

**Comment by mohebmithani** [comment]
> I think you can do a merge commit, then I'll do squash here in UI :) Probably it will be the easiest way to go

Merge commit is done. Thankyou for all the responses

**Comment by Stranger6667** [comment]
The failure is caused by the recent change in Hypothesis, so I will skip those tests for now until the issue is resolved upstream (I think that would be the right direction).

At this point, I will take care of some small cleanups in this PR and make everything green today :) Thank you so much for your contribution

**Comment by mohebmithani** [comment]
Your welcome @Stranger6667 and much appreciated for all the help along the way.

**Pull request merged**
