### PR TITLE
issue-1614/add-httpx-dependency

### PR DESCRIPTION
**Pull request by Bidaya0**
🚨Please review the [guidelines for contributing](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.rst) to this repository.

### Description
Please explain the changes you made here.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [x] All tests passing
- [ ] Added a changelog entry
- [ ] Extended the README / documentation, if necessary

try to fix : https://github.com/schemathesis/schemathesis/issues/1614

### CODE REVIEW

**Comment by Bidaya0** [comment]
Any idea about the ` FileNotFoundError` in windows?

I changed the pyproject.toml and locked it in linux.

Is there something I have not aware of?

**Comment by Bidaya0** [comment]
Added `atomicwrites` dependency on `win32` platform, which was present in `poetry.lock`  but not in `pyproject.toml`

**Comment by Stranger6667** [comment]
I think it would be better to update `pytest` to `7.1.3` instead as they [dropped](https://github.com/pytest-dev/pytest/blob/main/doc/en/changelog.rst#pytest-713-2022-08-31) `atomicwrites`

**Comment by Bidaya0** [comment]
> I think it would be better to update `pytest` to `7.1.3` instead as they [dropped](https://github.com/pytest-dev/pytest/blob/main/doc/en/changelog.rst#pytest-713-2022-08-31) `atomicwrites`

@Stranger6667 
I did this on the new commit, but it seems to never pass the test on windows.
Can you take a look, maybe someone who knows the project better will solve it faster.

**Comment by Stranger6667** [comment]
I'll work on fixing tests now

**Pull request merged**
