### PR TITLE
Relax colorama and typing-extensions

### LINKED ISSUE #1258: Relax requirement on colorama
E.g `^0.4.0`

Ref: https://github.com/aws/aws-cli/issues/5943

### PR DESCRIPTION
**Pull request by sobolevn**
🚨Please review the [guidelines for contributing](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.rst) to this repository.

### Description

Relaxed `colorama` and `typing-extension`. Got hit by it today.
Closes #1258 

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [ ] Added a changelog entry
- [ ] Extended the README / documentation, if necessary

None of those things 😢

### CODE REVIEW

**Comment by Stranger6667** [comment]
Thank you @sobolevn !

I plan to issue a new release this week :) Let me know if it is more urgent in your case

**Comment by sobolevn** [comment]
Btw, https://habr.com/ru/company/oleg-bunin/blog/576496/

**Comment by sobolevn** [comment]
> I plan to issue a new release this week :) Let me know if it is more urgent in your case

Nothing urgent, I am just playing around!

**Comment by Stranger6667** [comment]
> Btw, https://habr.com/ru/company/oleg-bunin/blog/576496/
> Oh, I see that you are the article's author 

Yep :) It took some time to write this up, but it is finally there :)

**Pull request merged**
