### PR TITLE
feat: XML serialization

### LINKED ISSUE #733: [FEATURE] XML serialization
If the API under test has `application/xml` input content type and `xml` fields that describe XML serialization we can create XML payloads from it

https://swagger.io/docs/specification/data-models/representing-xml/

### PR DESCRIPTION
**Pull request by Stranger6667**
Resolves #733

TODO:
- [ ] Decide on the `root` element name if it is not available - the case without references to `components` & an explicit name
- [ ] Check that everything works for OAS 2
- [x] Reject examples that lead to invalid XML
- [ ] More tests for unbound prefixes
- [x] Refactor code & add docs/comments

### CODE REVIEW

**Comment by afuetterer** [comment]
Awesome, thank you for prioritizing this!

**Comment by Stranger6667** [comment]
You are very welcome! Let me know how this feature fits your use case, I’d be keen to make further improvements :) I plan to implement more changes before releasing a new version, so in the case you’d like to try this feature, you’ll need to install the latest version from git repo

**Comment by afuetterer** [comment]
I will give it a try later this week and come back to you with potential feedback.

**Comment by Stranger6667** [comment]
Awesome!

**Pull request merged**
