### PR TITLE
ci: add python 3.9 builds #731

### PR DESCRIPTION
**Pull request by PrayagS**
### Description
As mentioned in #731,
- Added py39 to envlist in tox.ini
- Added Programming Language :: Python :: 3.9 classifier to classifiers in pyproject.toml
- Added 3.9 to the build.yml file inside the .github/workflows folder

### Checklist
- [ ] ~~Created tests which fail without the change (if possible)~~
- [ ] ~~All tests passing~~
- [ ] Added a changelog entry (Not sure whether a new entry is needed or not.)
- [ ] ~~Extended the README / documentation, if necessary~~

### CODE REVIEW

**Comment by PrayagS** [comment]
Did I jump on it too quickly? Maybe I need to wait for [setup-python](https://github.com/actions/setup-python) to add Python 3.9. Current version 3.9.0-rc.2 won't work I suppose.

**Comment by Stranger6667** [comment]
Hi @PrayagS !

Yes, I'd rather wait until the new Python version is released and added to GH action. 

Also, there are people who intended to work on this issue as well - It would be nice if you would communicate working on this issue with them in #731 before jumping in :) I hope it can help us to avoid duplicate work among different contributors

**Comment by PrayagS** [comment]
Gotcha @Stranger6667. And sorry for jumping right away.

**Comment by svtkachenko** [comment]
Looks like now it is possible to use range for versions:
[actions/setup-python#usage]( https://github.com/actions/setup-python#usage)
https://github.com/actions/setup-python/issues/20
https://github.com/actions/setup-python/issues/124

So  `'3.9-dev - 3.9.X'`  should start picking release version once it is available 🤔

**Comment by PrayagS** [comment]
So thanks to @svtkachenko, the 3.9 build job is working but during its execution, the test suite is throwing a `AssertionError` in `test/cli/test_cassettes.py`.

https://github.com/schemathesis/schemathesis/blob/512dff47bed6b3cee76d868f0d91b51cebe68159/test/cli/test_cassettes.py#L169

**Comment by Stranger6667** [comment]
Cool! I will take a look :)

**Comment by Stranger6667** [comment]
Hi! The problem was here - #788 

I fixed the problem and took your commits into a separate pull request (#790). Now it is merged :) Thank you very much for working on this

**Comment by PrayagS** [comment]
Thanks @Stranger6667. It was nice working on this and once again, sorry for jumping on the issue straight up. I'll make sure to communicate properly now onwards.

**Pull request closed without merging**
