### PR TITLE
Documentation additions for the cli

### PR DESCRIPTION
**Pull request by mdavis-xyz**
🚨Please review the [guidelines for contributing](https://github.com/schemathesis/schemathesis/blob/master/CONTRIBUTING.rst) to this repository.

### Description

* Explain the format of the `--auth` argument
* Explain how to use a spec from disk

### Checklist
- [ ] Created tests which fail without the change (if possible) - NA for documentation change
- [ ] All tests passing - NA for documentation change
- [ ] Added a changelog entry - do you need this for a small doc change?
- [X] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by mdavis-xyz** [comment]
The CI tests are failing. I'm not sure why:

```
Found 2 commit to check
+------------------------------------------+------------------+-------------------------------+
| HASH                                     | FAILURE          | TEXT                          |
+------------------------------------------+------------------+-------------------------------+
| 596a0e53c7b15ed59c45d9820f291fc5ae990c67 | category missing | clarify cli from spec on disk |
|                                          |                  |                               |
| 4bda135c6f306f3524997164eef1e63a802826d3 | category missing | document --auth format        |
|                                          |                  |                               |
+------------------------------------------+------------------+-------------------------------+
2 of 3 commits are not conventional commit compliant

Expected format is for example:      chore(ci): this is a test
Please see https://www.conventionalcommits.org for help on how to structure commits

Not all commits are conventional commits, please check the commits listed above
```

Is it because I have hyphens in my second commit message?

**Comment by mdavis-xyz** [comment]
Ah, [I see](https://www.conventionalcommits.org/en/v1.0.0/), ok I'll fix that.

**Comment by Stranger6667** [comment]
Hi @mdavis-xyz !

Thank you for adding this to our docs! :) I appreciate it :)

> do you need this for a small doc change?

No, it is ok without a changelog entry :)

**Comment by Stranger6667** [comment]
> Is it because I have hyphens in my second commit message?
> Ah, I see, ok I'll fix that.

I am glad that the issue is solved! Feel free to reach out to me in case if there will be any other build issues

**Pull request merged**
